"""Initial extraction helper. Later reviewed country/*.json files are authoritative.
Do not rerun this bootstrap to refresh the final package: it predates QA corrections.
Use build_country_library.py to reproduce exports from the curated packets.
"""
from pathlib import Path
import json,re
R=Path(__file__).resolve().parents[1]
def country(name,iso,priority,status,summary):
 return dict(country=name,iso2=iso,priority=priority,coverage_status=status,summary=summary,preferred_series_ids=[],search_log=[],sources=[],series=[],observations=[],limitations=[],review_checks=[],research_complete=True)
def source(c,id,title,publisher,url,date,file,locator,kind='industry_association',access='full_source',notes=''):
 c['sources'].append(dict(source_id=id,title=title,publisher=publisher,url=url,publication_date=date,retrieved_date='2026-09-09',source_type=kind,local_file=file,locator=locator,access_status=access,notes=notes))
def series(c,id,label,unit,scope,geo,pop,method,**kw):
 d=dict(series_id=id,label=label,measure='employment_stock',unit=unit,industry_scope=scope,occupation_scope='All roles in covered businesses, including creative, technical and business functions.',geography_basis=geo,geography_note='Domestic workers irrespective of citizenship or employer ownership are the comparison target; exact source rules below.',worker_status='Employees; other statuses unknown unless specified.',contractor_treatment='unknown',nationality_definition='Not reported.',method=method,population_basis=pop,sample_size='See observations.',comparability_group=id,chart_eligible=True,trend_eligible=False,index_2019_eligible=False,comparison_note='Separate source-native series. Do not sum with other series.',source_native_term=label,term_translation=label)
 d.update(kw);c['series'].append(d);return d
def obs(c,s,src,y,v,period,loc,**kw):
 d=dict(observation_id=f'{s}_{y}_{src}_{len(c["observations"])}',series_id=s,source_id=src,observation_period=period,year=y,value=v,value_low=None,value_high=None,status='reported',preferred=True,subgroup='all',denominator='All employment covered by this series.',source_locator=loc,publication_vintage=src,method_break=False,break_note='',derivation='',notes='')
 d.update(kw);c['observations'].append(d)
def search(c,route,query,url,outcome):c['search_log'].append(dict(route=route,query=query,url=url,outcome=outcome))
def save(c): (R/'country'/f'{c["iso2"]}.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n')

c=country('Cyprus','CY','primary','usable_series','CYGMA reports 1,438 people employed and paying taxes locally in 2019 and 4,320 in 2024. A 2025 report edition does not mean 2025 employment. Administrative coverage is broader than a pure games-publishing activity code.')
source(c,'CY_cygma2025','Cyprus Video Game Industry Report 2025','CYGMA; CBusiness Advisors; Registrar of Companies and CYSTAT','https://cygma.eu/wp-content/uploads/2026/08/Cyprus-Video-Game-Industry-Report-2025_by-CYGMA.pdf','2026-08-17','raw/CY/cygma2025.pdf','p15 employment chart; pp67-70 methodology')
series(c,'CY_local','People employed and paying taxes in Cyprus','people','Video game development/publishing company mapping; excludes iGaming as an intended scope. Administrative J58/J62 categories are imperfect proxies. Hardware, retail, venues and indirect jobs are not the intended total. Specialist services not separately quantified.','domestic_workplace','administrative_population','Company and tax/statistical data assembled by CBusiness Advisors. Report identifies broad NACE classification and omitted-head-office issues.',trend_eligible=True,index_2019_eligible=True,comparison_note='Continuous 2019-2024 chart from one report vintage; domestic tax employment is explicit. Index is a within-series change only. Pure core scope and contractor coverage remain imperfect.',geography_note='Source explicitly describes people employed and paying taxes in Cyprus. Citizenship and ownership not used as exclusions; offshore/remote treatment beyond this condition unknown.',worker_status='People employed and paying taxes; employee/founder/contractor/apprentice/intern split unknown.',contractor_treatment='Not separately specified; do not add contractor estimates.')
for y,v in [(2019,1438),(2020,1631),(2021,2166),(2022,3105),(2023,4057),(2024,4320)]:obs(c,'CY_local','CY_cygma2025',y,v,f'{y}; precise within-year reference not stated','p15 chart',status='estimated')
c['preferred_series_ids']=['CY_local'];c['limitations']=['Series comes from company and administrative mapping with imperfect activity-code boundaries.','Foreign citizenship, work permits, foreign ownership and staff abroad are not interchangeable; none is quantified by the employment chart.','No verified employment observations for 2015-2018 or 2025 in this source.']
search(c,'statistical_agency','CYSTAT employment enterprise NACE 58.21 games','https://www.cystat.gov.cy/en/StaticPage?id=1226','General employment tables found; no separately verified comprehensive games workforce. CYGMA combines administrative sources.')
search(c,'industry_association','CYGMA Cyprus video game industry report 2025 employment','https://cygma.eu/news/cyprus-video-game-industry-report-2025-published/','Full original 2025 report downloaded, release dated 17 August 2026; historical employment inspected.')
search(c,'local_language','Κύπρος απασχόληση έκδοση ηλεκτρονικών παιχνιδιών Στατιστική Υπηρεσία','https://library.cystat.gov.cy/Documents/Publication/EMPLOYMENT_ENT-NACE2-SIZE-2019-161220.pdf','Greek statistical-agency route located enterprise employment publication; broader classifications cannot substitute for the mapped games series.')
c['review_checks']=['Employment chart on PDF p15 rendered and visually checked against all six extracted values.','Latest observation and publication date separated.'];save(c)

c=country('Australia','AU','additional','usable_series','Two distinct measures are available: ABS domestic business employment (headcount) and IGEA full-time employment including FTEs and contractors. IGEA added nonresponding-studio estimates for FY2025; do not interpret that change as a consistent survey trend.')
source(c,'AU_agds2024','Australian Game Development Survey FY2024','IGEA; Bond University','https://igea.net/wp-content/uploads/2024/12/AGDS-2024-Report-Final.pdf',None,'raw/AU/agds2024.pdf','p6 historical table; pp4-5 footnotes; p12 methodology',notes='December 2024 release; exact publication day not confirmed in PDF.')
source(c,'AU_agds2025','Australian Game Development Industry Snapshot FY2025','IGEA; Bond University','https://igea.net/wp-content/uploads/2026/03/AGD-2025-Standalone-Infographic.pdf','2026-03-18','raw/AU/infographic2025.pdf','p1 employment and footnote; p3 method')
source(c,'AU_faq2025','FAQ: Australian game development survey FY2025 results','IGEA','https://igea.net/wp-content/uploads/2026/03/FAQ-Australian-game-development-survey-FY2025-results.pdf','2026-03-18','raw/AU/faq2025.pdf','Methodology change answer')
source(c,'AU_abs2022','Film, Television and Digital Games, Australia, 2021-22','Australian Bureau of Statistics','https://www.abs.gov.au/statistics/industry/technology-and-innovation/film-television-and-digital-games-australia/latest-release','2023-06-22','raw/AU/abs2022.html','Digital game development businesses: key figures and employment tables','government')
source(c,'AU_absmethod2022','Film, Television and Digital Games methodology, 2021-22','Australian Bureau of Statistics','https://www.abs.gov.au/methodologies/film-television-and-digital-games-australia-methodology/2021-22-financial-year','2023-06-22','raw/AU/abs-method2022.html','Scope; reference period; glossary Employment at end June','government')
scope='Australian game development studios including contracted development and all internal roles; broader publishing distribution, hardware, retail, venues, esports and indirect employment not included as separate sectors.'
series(c,'AU_igea_survey','IGEA full-time employment incl. contractors','source_reported_full_time_employment',scope,'domestic_workplace','survey_sample','Voluntary studio survey, changing respondent pool; no verified full-population expansion for historical series.',worker_status='Source says full-time employees, includes full-time equivalents and contractors. Conversion of every contractor to FTE is not established. Founders/interns/apprentices not separately specified.',contractor_treatment='Included in source total; no separate count. Do not label as pure employee headcount or pure FTE.',comparison_note='Snapshots only; changing sample sizes and source treatment preclude clean cross-country index.',source_native_term='No. of employees; full time employees*',term_translation='Source footnote: includes full-time equivalents and contractors.')
vals=[(2016,842,63),(2017,928,114),(2019,1275,143),(2020,1245,97),(2021,1327,187),(2022,2104,102),(2023,2458,111),(2024,2465,137)]
for y,v,n in vals:obs(c,'AU_igea_survey','AU_agds2024',y,v,f'FY ending 30 June {y}','p6 historical table',notes=f'{n} companies in source historical table; {y} employment reference within fiscal year not further resolved.')
series(c,'AU_igea_augmented','IGEA survey plus studio estimates','source_reported_full_time_employment',scope,'domestic_workplace','national_estimate','FY2025 voluntary responses from 141 studios plus third-party estimates for selected nonrespondents (FAQ). Not a demonstrated exhaustive national census.',contractor_treatment='Included in total per p1 footnote; no separate count or full conversion specification.',worker_status='Full-time employees including FTEs and contractors; other statuses unknown.',sample_size='141 usable studio responses; over 600 invited; supplementary estimates for selected nonrespondents.',comparison_note='Methodology break from historical survey. Source_native total retained; do not calculate a consistent 2024-25 decline.')
obs(c,'AU_igea_augmented','AU_agds2025',2025,2443,'FY 1 July 2024 to 30 June 2025; collected Oct 2025-Jan 2026','p1; p3',status='estimated',method_break=True,break_note='AU_faq2025 describes added employment estimates for nonresponding studios.')
series(c,'AU_abs_headcount','ABS people employed in development businesses','people','Digital game development businesses, own-title and fee-for-service production; all internal roles. Broader hardware, retail, venues and indirect jobs excluded. Other activities within multi-activity business units may remain.','domestic_workplace','national_estimate','Census of known digital game development businesses; ABS Business Register plus industry sources. Last pay period ending June. Scope/classification changes require caution across survey years.',worker_status='Working proprietors and partners, payroll employees including paid-leave and workers compensation, and contract workers paid through payroll included. Non-salaried directors and volunteers excluded. Apprentices and interns not separately quantified.',contractor_treatment='Payroll contract workers included. Payments to self-employed contractors are outside wages and salaries; off-payroll contractor headcount not included as an employee count.',comparison_note='Headcount snapshots, no 2019 baseline. ABS cautions comparisons to 2015-16 as categories changed; do not join to IGEA.',sample_size='Census of known in-scope businesses; response count not extracted.')
for y,v in [(2016,734),(2022,2225)]:obs(c,'AU_abs_headcount','AU_abs2022',y,v,f'Last pay period ending June {y}','Digital game development businesses: key figures table',status='estimated',method_break=y==2022,break_note='ABS cautions that expanded/grouped data categories may not be directly comparable to 2015-16.' if y==2022 else '')
c['preferred_series_ids']=['AU_abs_headcount','AU_igea_survey','AU_igea_augmented']
c['limitations']=['Source-native full-time employment measure must not be renamed pure FTE.','IGEA FY2025 supplementary employment estimates alter coverage; 2024 and 2025 not used for measured decline.','2015 and 2018 IGEA employment not located; ABS series is sparse. No verified nationality breakdown.']
for route,q,url,out in [('statistical_agency','ABS Film television digital games employment census','https://www.abs.gov.au/statistics/industry/technology-and-innovation/film-television-and-digital-games-australia/latest-release','Inspected current original release and detailed glossary; 2016 and 2022 employment retained.'),('industry_association','IGEA game development survey 2015 2025 employment archive','https://igea.net/2026/03/agds-2025/','Original historical table and latest infographic/FAQ inspected.'),('local_language','Australia game development employment FTE contractors national survey','https://igea.net/wp-content/uploads/2024/12/AGDS-2024-Report-Final.pdf','English local-language sources inspected; footnotes distinguish FTEs/contractors from ABS persons.')]:search(c,route,q,url,out)
c['review_checks']=['Historical table on p6 rendered and visually checked; values and annual sample sizes extracted together.','ABS employment definition read in glossary; payroll contractors preserved.','FY2025 FAQ checked for scope change.'];save(c)

c=country('Israel','IL','additional','context_only','Deloitte/GameIS reports about 4,000 workers in 2017 and 14,000 in 2021 across a broad ecosystem. Domestic-only employment is not established, and the company roster includes global offices and real-money gaming. These are context estimates, excluded from the domestic comparison.')
source(c,'IL_gameis2021','The Israeli Video Games Ecosystem, 2021 edition','Deloitte Israel and GameIS','https://www.vccafe.com/wp-content/uploads/2022/12/GameIS-Report-2021-0722.pdf','2022-07-11','raw/IL/gameis2021.pdf','p22 employment; pp23-25 company profiles; p29 categories; pp31-32 company roster','research_partner',notes='Original authored report preserved on a public mirror. Copyright 2022; contemporary Hebrew release dated 11 July 2022. Mirror upload December 2022 is not observation date.')
series(c,'IL_ecosystem','Broad Israeli-company ecosystem estimate','people','Game publishing plus supportive technologies and platforms; roster includes 888 real-money gambling. No clean domestic core-only subset verified.','unknown','unknown','Company ecosystem mapping using Start-Up Nation, Crunchbase, PitchBook and company websites; no domestic reconciliation or sampling method exposed for aggregate.',chart_eligible=True,geography_note='Israel-based and global companies operating in Israel; adjacent profiles quote company headcounts across worldwide offices. Cannot establish that aggregate excludes overseas workers.',worker_status='Reported employees/workers; FTE, contractors, freelancers, founders, interns and agency staff unresolved.',comparison_note='Context-only snapshots. Unresolved geography and wider industry scope bar national ranking, trends and index.')
for y,v in [(2017,4000),(2021,14000)]:obs(c,'IL_ecosystem','IL_gameis2021',y,v,f'{y}; exact census date unspecified','p22 Number of employees',status='estimated',value_qualifier='approximately',notes='Approximate source value, not precise census. Domestic workplaces unresolved.')
c['limitations']=['Company worldwide headcount may be mixed with domestic operations; no subtraction fabricated.','Game-publishing share of employees (73%) does not resolve geography or gambling coverage; no adjusted core total derived.','No current 2024-26 national count verified; repeating 14,000 in a newer article does not create a newer observation.']
search(c,'statistical_agency','הלשכה המרכזית לסטטיסטיקה תעשיית משחקי מחשב מועסקים','https://www.cbs.gov.il/he/publications/DocLib/2024/shnaton2024.pdf','General high-tech/yearbook employment found, no separately established comprehensive games workforce.')
search(c,'industry_association','GameIS Deloitte Israeli game industry report employees','https://www.gameis.org.il/','Association reviewed; full Deloitte/GameIS report obtained from public mirror.')
search(c,'local_language','דוח גיימינג ישראל 2021 14000 עובדים 4000 דלויט','https://www.funder.co.il/article/136571','Hebrew 11 July 2022 coverage corroborates report release and figures; no proof of domestic-only coverage.')
c['review_checks']=['Aggregate employment read on p22; adjacent global-office company profiles and broad roster checked.'];save(c)

c=country('New Zealand','NZ','additional','usable_series','NZGDA annual survey observations span 2015-2025. Source units alternate between full-time employees, workers and FTEs, while respondents change. Later editions mention overseas staff. Keep snapshots and visa composition separate; no national index.')
samples={2015:27,2016:38,2017:29,2018:41,2019:39,2020:42,2021:63,2022:74,2023:93,2024:100,2025:None}
for y in range(2015,2026):
 if y==2016:
  url='https://igea.net/2016/08/nz-video-game-exports-continue-to-grow/';date='2016-08-03';file='raw/NZ/survey2016.html';title='NZ video game exports continue to grow (NZGDA release)'
 else:
  p=R/f'raw/NZ/survey{y}.html';h=p.read_text();date=re.search(r'"datePublished"\s*:\s*"([^"]+)',h).group(1)[:10];file=f'raw/NZ/survey{y}.html'
  url=f'https://www.nzgda.com/blog/news/survey{y}' if y<=2021 else f'https://www.nzgda.com/blog/news/nz-interactive-media-industry-survey-{y}' if y<=2023 else 'https://www.nzgda.com/blog/news/2024-industry-survey-results' if y==2024 else 'https://www.nzgda.com/blog/new-zealand-game-development-industry-breaks-records'
  title=f'NZGDA industry survey {y}'
 source(c,f'NZ_survey{y}',title,'NZGDA; Tim Thorpe Consulting / Premium Research; IGEA hosts 2016 release',url,date,file,'Employment / Job Creation / Skills / survey methodology paragraphs',access='public_summary',notes='2025 site publication 25 Nov 2025; same NZGDA release appeared on Scoop 26 Sep 2025. Retained source-native publication date.')
scope='Games and interactive studios; later surveys explicitly include VR/AR, education technology and serious games. Contract development and studio services included; hardware, retail, venues and indirect employment not the intended scope.'
method='Annual voluntary association studio survey; sample sizes and source wording vary. No documented national gross-up or full-time-equivalence conversion across all years.'
for id,label,unit in [('NZ_fulltime','Survey full-time employees / roles','full_time_positions'),('NZ_workers','Survey workers; hours not specified','people'),('NZ_fte','Survey full-time equivalents','FTE')]:
 series(c,id,label,unit,scope,'mixed','survey_sample',method,geography_note='New Zealand studios, all ownerships; 2017/18 explicitly workers in NZ studios. Later respondents include remote teams in NZ and overseas. 2024 reports 31 FTE Australia and 85 other overseas, without proving if included in headline. No subtraction made.',worker_status='Source wording shown per observation. Contractors, founders, agency staff, apprentices and interns not separately defined.',comparison_note='No line trend or 2019 index: variable sample, occupational scope and unit wording. Overseas-office inclusion unresolved in later summaries.')
values=[(2015,568,'NZ_fulltime'),(2016,475,'NZ_fte'),(2017,500,'NZ_workers'),(2018,550,'NZ_fulltime'),(2019,683,'NZ_workers'),(2020,747,'NZ_fulltime'),(2021,969,'NZ_fte'),(2022,1070,'NZ_fulltime'),(2023,1106,'NZ_fte'),(2024,1097,'NZ_fte'),(2025,1418,'NZ_fte')]
for y,v,s in values:
 src=f'NZ_survey{2025 if y==2024 else y}';obs(c,s,src,y,v,f'FY ending 31 March {y}; employment at March where specified','Employment / Job Creation paragraph',notes=f'Survey respondents: {samples[y] if samples[y] else "not stated in release"} studios. '+('2024 value is explicit comparison in 2025 release; not a value inferred from a percentage.' if y==2024 else ''))
for id,label,term in [('NZ_visa_current','Staff currently on work visas','Current visa status. 2019 says work visas; other years specify work-supported visas. Not nationality and not all migrants.'),('NZ_visa_ever','Staff currently or formerly on work-supported visas','Current OR prior work-supported visa; not comparable to current status.')]:
 series(c,id,label,'percent',scope,'mixed','survey_sample',method,measure='visa_share',nationality_definition=term,comparison_note='Source-reported rounded share of survey workforce. Visa status is not citizenship; do not use to infer number of foreign nationals. No multiplication into national totals.')
for y,v in [(2018,15),(2019,14),(2021,13),(2022,6),(2023,8)]:obs(c,'NZ_visa_current',f'NZ_survey{y}',y,v,f'Survey workforce in FY ending March {y}','Skills/work-supported visas paragraph',subgroup='current work-supported visa',denominator=f'Workforce in {samples[y]} responding studios; source employment total is '+str(dict((a,b) for a,b,_ in values)[y])+'. Rounded share; source mixes people and FTE wording.')
obs(c,'NZ_visa_ever','NZ_survey2020',2020,15,'FY ending 31 March 2020','Highlights: 111 employees currently or previously on work-supported visas',subgroup='current or former work-supported visa',denominator='747 full-time workers in 42 studio responses; 111 employees numerator.',notes='Source share is rounded; historical and current visa statuses combined.')
series(c,'NZ_visa_counts','Survey staff on work-supported visas','people',scope,'mixed','survey_sample',method,measure='visa_count',nationality_definition='Visa status, not foreign nationality.',chart_eligible=False,comparison_note='Counts retained for denominator audit. 2024 page conflicts (97 and 98); neither selected.')
for y,v in [(2018,84),(2021,128),(2022,63),(2023,90),(2024,97),(2024,98)]:obs(c,'NZ_visa_counts',f'NZ_survey{y}',y,v,f'May 2024 for detailed 98 statement; otherwise survey FY {y}' if y==2024 else f'FY {y}','Skills / visa-supported staff paragraphs',preferred=y!=2024,subgroup='current work-supported visa',denominator=f'{samples[y]} studio respondents',notes='2024 opening says 97, detailed section says 98 as of May; unresolved internal conflict, excluded from charts.' if y==2024 else '')
series(c,'NZ_overseas','Staff based overseas in responding studios','FTE',scope,'company_worldwide','survey_sample',method,measure='other',chart_eligible=False,comparison_note='Overseas locations are not nationality. Inclusion in headline employment unresolved; do not subtract automatically.')
for subgroup,v in [('Australia',31),('Other overseas locations',85)]:obs(c,'NZ_overseas','NZ_survey2024',2024,v,'2024 survey; exact staff reference date not stated','Overseas Staff',subgroup=subgroup,denominator='100 studio respondents; total overseas count not separately reconciled')
c['preferred_series_ids']=['NZ_fulltime','NZ_workers','NZ_fte']
c['limitations']=['Respondent pool varies from 27 studios in 2015 to 100 in 2024; 2025 response count not stated in release.','2019 workers are not automatically treated as 2019 FTEs.','Visa composition has changing definitions and rounded percentages; 2024 contains a 97/98 internal conflict.','Foreign ownership of studios is distinct from foreign citizenship and work abroad.','2015-2025 source-native observations are present; no claim of constant population or scope.']
search(c,'statistical_agency','Statistics NZ ANZSIC game development workforce national employment','https://datainfoplus.stats.govt.nz/item/nz.govt.stats/fe39918b-ed28-4775-bad4-eaab6bbea68f','Stats NZ employment-indicator methodology inspected: broad industry categories, no separately identified game-development count. Ministry for Culture evidence brief also states codes historically could not directly measure games jobs and cites NZGDA. MBIE rebate review download did not return PDF; rebate cohort is not whole population.')
search(c,'industry_association','NZGDA industry survey archive 2015 through 2025','https://www.nzgda.com/blog/category/Reports','Annual original NZGDA releases recovered; 2016 original release hosted by IGEA.')
search(c,'local_language','New Zealand game developers survey employees visas contractors','https://www.nzgda.com/blog/news/2024-industry-survey-results','English local sources checked; current-versus-former visa status, overseas offices and contradictory 2024 count retained.')
c['review_checks']=['Source metadata publication dates extracted separately from FY periods.','2025 arithmetic: 1418/1097 - 1 = 29.26%, source rounded growth is 29.2%.','No annual headcount-to-FTE conversion or overseas subtraction.'];save(c)
c=country('Turkey','TR','additional','usable_snapshot','TOGED supplies a 2023 employment estimate of 10,777 in the EGDF report. The questionnaire requests FTEs including remote workers abroad, so this is not strictly domestic workplace employment. A much lower 2,500-3,000 secondary estimate cannot be verified in its cited original and remains unplotted context.')
source(c,'TR_egdf2023','2023 European Video Games Industry Insight Report: Turkey','EGDF / TOGED; supported by Video Games Europe','https://www.egdf.eu/wp-content/uploads/2025/08/2023-European-video-games-industry-insight-report.pdf',None,'raw/TR/egdf2023.pdf','p57 Turkey chart; pp74-76 questionnaire',notes='Published August 2025; exact day not verified on original release. National-association data compiled by EGDF.')
source(c,'TR_invest2025','The State of Turkish Gaming Ecosystem 2025','Investment and Finance Office of the Presidency of Türkiye; startups.watch','https://www.invest.gov.tr/en/library/publications/lists/investpublications/the-state-of-turkish-gaming-ecosystem-2025.pdf?download=',None,'raw/TR/invest2025.pdf','p12 studio size; whole report screened','government',notes='2025 edition with 2026 references; no total workforce recovered. Original file download requires download query. Scope figures concern companies and investments, not a workforce census.')
source(c,'TR_market2023','Türkiye Game Market Report 2023','Gaming in Türkiye','https://investgame.net/wp-content/uploads/2024/07/turkiye-game-market-report-2023_compressed.pdf',None,'raw/TR/market2023.pdf','Full report searched for employment; studio and venue tables','research_partner',notes='2023 report on public mirror; no verification of the 2500-3000 workforce attribution made by the thesis.')
source(c,'TR_market2025','Türkiye Game Market Report 2025','Gaming in Türkiye','https://investgame.net/wp-content/uploads/2026/02/2026-02-17-trkiye_game_market_report_2025-compressed_wp.pdf','2026-02-17','raw/TR/market2025.pdf','Full report screened; company/industry sections','research_partner',notes='365-page original report on public mirror; includes market size and ecosystem commentary, no verified total national workforce in inspected text. Publisher archive confirms release date.')
source(c,'TR_thesis2025','Rethinking Auteur and Authority on Creative Actors in Turkish Video Game Industry','Yiğit Tarlabölen, Başkent University','https://acikerisim.baskent.edu.tr/server/api/core/bitstreams/ecfd58a7-4c0f-4e93-a1a3-7449f29ea70a/content',None,'raw/TR/thesis2025.pdf','printed p4 / PDF p14','secondary','secondary_only',notes='2025 thesis; exact publication date unresolved. Its population estimate is attributed to Gaming in Türkiye 2023, not measured by the thesis interviews.')
series(c,'TR_toged','TOGED developer/publisher workforce estimate','FTE','Game development and publishing; excludes non-development specialist services, pure asset suppliers, retail and distribution in EGDF questionnaire. Hardware, venues, gambling and esports boundaries not individually specified for Turkey.','mixed','national_estimate','TOGED national submission to EGDF. Questionnaire requests full-time equivalent employees, entrepreneurs and in-house freelancers; country-specific sampling details not published.',geography_note='Includes direct remote employees in third countries under EGDF rules. Excludes staff of foreign subsidiaries and subcontractor companies abroad. Foreign-owned local subsidiaries are reported independently; nationality is not an exclusion.',worker_status='EGDF FTE definition includes employees, entrepreneurs and in-house freelancers. Agency staff, apprentices and interns not separately specified; Turkey-specific implementation not documented.',contractor_treatment='In-house freelancers in requested FTE measure; foreign subcontractor companies excluded. No separate contractor count.',comparison_note='Usable association snapshot only; mixed remote geography and missing local method prevent strict domestic comparison or a trend. No 2019 observation.',source_native_term='Number of people working in the industry',term_translation='The chart calls this people; questionnaire p76 specifies FTE. Turkey-specific conversion is not independently documented.')
obs(c,'TR_toged','TR_egdf2023',2023,10777,'2023; precise reference date not stated','p57 employment column, 2023 bar',status='estimated',notes='The nearby 3,300 is turnover in million euros, not 2019 employment. All 2019-2022 employment bars are N/A.')
series(c,'TR_secondary_range','Unverified secondary workforce range','people','Claimed game developers and indie teams; industry exclusions unresolved.','unknown','unknown','Thesis repeats attributed population estimate; original calculation not recovered.',chart_eligible=False,comparison_note='Retained separately as secondary context. Conflicts with TOGED estimate; insufficient evidence to reconcile scope or date.')
obs(c,'TR_secondary_range','TR_thesis2025',2023,None,'Claimed 2023 national figure','printed p4 / PDF p14',value_low=2500,value_high=3000,status='estimated',preferred=False,notes='Claimed original source is Gaming in Türkiye 2023, but inspection did not verify this range. No midpoint or gap-filling.')
c['preferred_series_ids']=['TR_toged']
c['limitations']=['No verified employment observations for 2015-2022 or later than 2023; later market reports do not establish later workforce counts.','EGDF requests FTEs but the country chart says people; unit implementation and national estimation method are not exposed.','Remote workers abroad remain within TOGED/EGDF measure; it is not a residents-only or workplace-only total.','Secondary estimate 2500-3000 is unresolved, not an alternative preferred national total.']
search(c,'statistical_agency','TÜİK oyun geliştirme istihdam çalışan sayısı 58.21','https://veriportali.tuik.gov.tr/tr/press/54059','General labor-force statistics found; no games-specific national extraction verified. Invest Türkiye 2025 report downloaded and screened; studio size and investment data do not give a national total.')
search(c,'industry_association','TOGED oyun sektörü çalışan istihdam rapor EGDF','https://toged.org/','Association website checked; TOGED submission located in original EGDF report and employment bar visually inspected.')
search(c,'local_language','Türkiye oyun sektörü raporu çalışan 2500 3000 2023 2025','https://www.turkiyeoyunsektoruraporu.com/tr/turkiye-oyun-sektoru-raporlari/','Local archive and 2023/2025 reports checked; thesis range retained as unverifiable secondary attribution.')
c['review_checks']=['PDF p57 rendered and visually checked, preventing revenue3300 from being misread as workers.','EGDF p76 employment definition inspected for FTE, founders, freelancers and remote workers.','2023 and 2025 market report text searched; secondary claim not verified in original.'];save(c)
print('Wrote CY AU IL NZ TR')
